/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsModelsRouteImport } from './routes/settings.models'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsSandboxRouteImport } from './routes/settings.sandbox'
import { Route as SettingsSearchRouteImport } from './routes/settings.search'
import { Route as SettingsSkillsRouteImport } from './routes/settings.skills'
import { Route as ApiPublicRunTickRouteImport } from './routes/api/public/run-tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSandboxRoute = SettingsSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSearchRoute = SettingsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiPublicRunTickRoute = ApiPublicRunTickRouteImport.update({
  id: '/api/public/run-tick',
  path: '/api/public/run-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/sandbox': typeof SettingsSandboxRoute
  '/settings/search': typeof SettingsSearchRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/api/public/run-tick': typeof ApiPublicRunTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/sandbox': typeof SettingsSandboxRoute
  '/settings/search': typeof SettingsSearchRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/api/public/run-tick': typeof ApiPublicRunTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/sandbox': typeof SettingsSandboxRoute
  '/settings/search': typeof SettingsSearchRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/api/public/run-tick': typeof ApiPublicRunTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/unlock'
    | '/api/chat'
    | '/chat/$chatId'
    | '/settings/integrations'
    | '/settings/models'
    | '/settings/providers'
    | '/settings/sandbox'
    | '/settings/search'
    | '/settings/skills'
    | '/api/public/run-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/unlock'
    | '/api/chat'
    | '/chat/$chatId'
    | '/settings/integrations'
    | '/settings/models'
    | '/settings/providers'
    | '/settings/sandbox'
    | '/settings/search'
    | '/settings/skills'
    | '/api/public/run-tick'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/unlock'
    | '/api/chat'
    | '/chat/$chatId'
    | '/settings/integrations'
    | '/settings/models'
    | '/settings/providers'
    | '/settings/sandbox'
    | '/settings/search'
    | '/settings/skills'
    | '/api/public/run-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  UnlockRoute: typeof UnlockRoute
  ApiChatRoute: typeof ApiChatRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  ApiPublicRunTickRoute: typeof ApiPublicRunTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sandbox': {
      id: '/settings/sandbox'
      path: '/sandbox'
      fullPath: '/settings/sandbox'
      preLoaderRoute: typeof SettingsSandboxRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/search': {
      id: '/settings/search'
      path: '/search'
      fullPath: '/settings/search'
      preLoaderRoute: typeof SettingsSearchRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/public/run-tick': {
      id: '/api/public/run-tick'
      path: '/api/public/run-tick'
      fullPath: '/api/public/run-tick'
      preLoaderRoute: typeof ApiPublicRunTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsSandboxRoute: typeof SettingsSandboxRoute
  SettingsSearchRoute: typeof SettingsSearchRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsSandboxRoute: SettingsSandboxRoute,
  SettingsSearchRoute: SettingsSearchRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  UnlockRoute: UnlockRoute,
  ApiChatRoute: ApiChatRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  ApiPublicRunTickRoute: ApiPublicRunTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
