/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'
import { Route as SettingsE2bRouteImport } from './routes/settings.e2b'
import { Route as SettingsModelsRouteImport } from './routes/settings.models'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsSkillsRouteImport } from './routes/settings.skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsE2bRoute = SettingsE2bRouteImport.update({
  id: '/e2b',
  path: '/e2b',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/settings/e2b': typeof SettingsE2bRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/skills': typeof SettingsSkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/settings/e2b': typeof SettingsE2bRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/skills': typeof SettingsSkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/settings/e2b': typeof SettingsE2bRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/skills': typeof SettingsSkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/unlock'
    | '/api/chat'
    | '/chat/$chatId'
    | '/settings/e2b'
    | '/settings/models'
    | '/settings/providers'
    | '/settings/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/unlock'
    | '/api/chat'
    | '/chat/$chatId'
    | '/settings/e2b'
    | '/settings/models'
    | '/settings/providers'
    | '/settings/skills'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/unlock'
    | '/api/chat'
    | '/chat/$chatId'
    | '/settings/e2b'
    | '/settings/models'
    | '/settings/providers'
    | '/settings/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  UnlockRoute: typeof UnlockRoute
  ApiChatRoute: typeof ApiChatRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/e2b': {
      id: '/settings/e2b'
      path: '/e2b'
      fullPath: '/settings/e2b'
      preLoaderRoute: typeof SettingsE2bRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsE2bRoute: typeof SettingsE2bRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsE2bRoute: SettingsE2bRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  UnlockRoute: UnlockRoute,
  ApiChatRoute: ApiChatRoute,
  ChatChatIdRoute: ChatChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
